# Site settings
title: CR Blog
SEOTitle: 曹锐的博客 | CR Blog
header-img: img/post-bg-desk.jpg
email: lixing.jian@outlook.com
description: "All that glitters is not gold."
keyword: "BY, BY Blog, 李湖隐的博客, lihuyin,Constantine Bellefield"
